---
title: "CITY_US"
output:
    html_document:
        df_print: paged
---


```{r, include=FALSE, warning=FALSE, message = FALSE}
knitr::opts_chunk$set(fig.width = 8, fig.height = 8)
# knitr::opts_chunk$set(
#     # This should allow Rmarkdown to locate the data
#     root.dir = rprojroot::find_rstudio_root_file()
# )
library(readxl)
library(reshape2)
library(ggplot2)
library(GGally)
library(stringr)
library(dplyr)
library(correlation) # cor_sort
library(forcats)
library(tidyr)
library(symmetry)
```

Ввод данных

Помечаю некорректные данные как NA.
Удаляю города из Аляски.

```{r, warning=FALSE, message = FALSE}
if (interactive() & !str_ends(getwd(), "R/Statistical_Analysis_2022/CITY_US/Tkachenko")) 
    setwd("R/Statistical_Analysis_2022/CITY_US/Tkachenko")


data <- read_excel("../CITY_US.STD/CITY_shortname.xls")

data[data == "NA"] <- NA
data$INCOME[data$INCOME < 100] <- NA

data <- data %>% filter(STATE != "AK")
data[, -(1:2)] <- data.frame(lapply(data[, -(1:2)], as.numeric))

print(head(data))
# print(names(data))
```

```{r, warning=FALSE, message = FALSE, include=FALSE}
temper_split <- mean(data$TEMPER)
data$F_TEMPER <- factor(ifelse(data$TEMPER >= temper_split, "hot", "cold"))

precep_split <- 20
data$F_PRECEP <- factor(ifelse(data$PRECEP >= precep_split, "big", "small"))

labor_split <- 5
data$F_LABOR <- factor(ifelse(data$LABOR >= labor_split, "big", "small"))

pop_ch_split <- 0
data$F_POP_CH <- factor(ifelse(data$POP_CH >= pop_ch_split, "growth", "decrease"))
```

```{r, warning=FALSE, message = FALSE}

names <- names(data)
fullnames <- names(read_excel("../CITY_US.STD/CITY.xls"))
# print(fullnames)

names_id <- c("CITY", "STATE", names[str_starts(names, "F_")])
names_no_ranks <- names[!str_starts(names, "R_")]
names_ranks <- names[str_starts(names, "R_")]
```

функция, которая логарифмирует, если это сделает выборку симметричнее

```{r, warning=FALSE, message = FALSE}

log_asymmetric <- function(x) {
    if (min(x[!is.na(x)]) < 0) {
        return(x)
    }
    if (symmetry_test(x[!is.na(x)], "SGN")$p.value <
        symmetry_test(log(x[!is.na(x)]), "SGN")$p.value) {
        return(log(x))
    } else {
        return(x)
    }
}
```

```{r, warning=FALSE, message = FALSE, include=FALSE}
data_logged <- data %>%
    mutate(across(names[!str_detect(names, "R_|F_|CITY|STATE")], log_asymmetric))

plot_all_density <- function(data, aes) {
    ggplot(data, aes) +
        theme_bw() +
        # geom_density() +
        geom_histogram(aes(y = ..density..), bins = 15) +
        facet_wrap(~variable, scales = "free") +
        geom_line(aes(y = dnorm(value,
            mean = tapply(value, variable, mean, na.rm = TRUE)[PANEL],
            sd = tapply(value, variable, sd, na.rm = TRUE)[PANEL]
        )), color = "black", linetype = 2) +
        theme(legend.position = "bottom") +
        labs(x = "", y = "")
}

data_melt <- melt(data[, names_no_ranks], id = names_id)

if (interactive()) pdf(file = "no_ranks_plots.pdf")
# plot_all_density(data_melt, aes(value, color = F_LABOR)) +
#     scale_color_manual(values = c("blue", "red"))
plot_all_density(data_melt, aes(value))
if (interactive()) dev.off()
```

```{r, warning=FALSE, message = FALSE, include=FALSE}
data_logged_melt <- melt(data_logged[, names_no_ranks], id = names_id)
if (interactive()) pdf(file = "no_ranks_logged_plots.pdf")
plot_all_density(data_logged_melt, aes(value))
if (interactive()) dev.off()

# plot_all_density(data_logged_melt, aes(value, color = F_TEMPER)) +
#     scale_color_manual(values = c("blue", "red"))

# plot_all_density(data_logged_melt, aes(value, color = F_PRECEP)) +
#     scale_color_manual(values = c("blue", "red"))

# plot_all_density(data_logged_melt, aes(value, color = F_LABOR)) +
#     scale_color_manual(values = c("blue", "red"))

# plot_all_density(data_logged_melt, aes(value, color = F_POP_CH)) +
#     scale_color_manual(values = c("blue", "red"))
```


```{r, warning=FALSE, message = FALSE, include=FALSE}
if (interactive()) pdf(file = "cor_matrix.pdf")
ggplot(melt(cor(data_logged[, !names %in% c(names_id, names_ranks)], method = "pearson", use = "pairwise.complete.obs"))) +
    geom_raster(aes(x = Var2, y = Var1, fill = value)) +
    scale_fill_gradient2() +
    theme_dark() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
if (interactive()) dev.off()

if (interactive()) pdf(file = "cor_sort_matrix.pdf")
ggplot(melt(cor_sort(cor(data_logged[, !names %in% c(names_id, names_ranks)], method = "pearson", use = "pairwise.complete.obs")))) +
    geom_raster(aes(x = Var2, y = Var1, fill = value)) +
    scale_fill_gradient2() +
    theme_dark() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
if (interactive()) dev.off()
```



Выбираю только интересные признаки.
Логарифмирую те признаки, которые от этого станут симметричнее 
```{r, warning=FALSE, message = FALSE}
names_interesting <- c("AREA", "POP80", "POP92", "POPDEN", "CRIME", "BORN_F", "POVERT", "INCOME", "UNEMP", "TEMPER")

data_interesting <- data[, names_interesting]

data_interesting_logged <- data_interesting %>%
    mutate(across(everything(), log_asymmetric))
```


Скаттерплот

```{r, warning=FALSE, message = FALSE}
if (interactive()) pdf("ggpairs_logged.pdf")
ggpairs(
    data_interesting_logged,
    lower = list(continuous = wrap("points", alpha = 0.5, size = 0.3)),
    diag = list(continuous = "barDiag")
)
if (interactive()) dev.off()
```

Матрица корреляций

```{r, warning=FALSE, message = FALSE}

data_interesting_logged <- data_interesting_logged %>%
    relocate(TEMPER, AREA, POP92, POP80, POPDEN, INCOME, BORN_F, UNEMP, POVERT, CRIME)

if (interactive()) pdf(file = "cor_matrix.pdf")
ggplot(melt(cor(data_interesting_logged, method = "pearson", use = "pairwise.complete.obs"))) +
    geom_raster(aes(x = Var2, y = Var1, fill = value)) +
    scale_fill_gradient2() +
    theme_dark() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
if (interactive()) dev.off()
```