---
title: "Partial_correlation"
output:
    html_document:
        df_print: paged
---



```{r, include=FALSE}
knitr::opts_chunk$set(fig.width = 8, fig.height = 8)

library(readxl)
library(reshape2)
library(ggplot2)
library(GGally) # pairwise plot
library(stringr) # str_squish

library(correlation) # cor_sort
library(tidyr) # drop.na()
library(ppcor)
library(dplyr) # dataframe
# setwd("R/Statistical_Analysis_2022/Partial_Correlation_CARDATA/Tkachenko")
```








```{r}
data <- read_excel("../CARDATA.xls")
data <- data %>%
    mutate(
        ROW = NULL,
        MPG = 1 / MPG,
        ACCEL = 1 / ACCEL,
        PRICE = log(PRICE)
    ) %>%
    rename(GPM = MPG) %>%
    filter(CYLINDER %in% c(4, 6, 8)) %>%
    select(-MAKE, -MODEL) %>%
    drop_na()

data_factor <- data %>%
    mutate(
        CYLINDER = as.factor(CYLINDER),
        YEAR = as.factor(YEAR),
        ORIGIN = as.factor(ORIGIN),
    )
```


```{r}

# pdf(file = "ggpairs.pdf")
ggpairs(data_factor,
    lower = list(combo = wrap("facethist", bins = 10)),
    diag = list(continuous = wrap("barDiag", bins = 10))
) + ggtitle("ggpairs")
# dev.off()
```


```{r}
# pdf(file = "ggpairs_grouped_cylinder.pdf")
ggpairs(data_factor,
    aes(colour = CYLINDER),
    upper = list(continuous = wrap("cor", digits = 2)),
    lower = list(combo = wrap("facethist", bins = 10)),
    diag = list(continuous = wrap("barDiag", bins = 10)),
) + ggtitle("ggpairs_grouped_cylinder")
# dev.off()
```

```{r}
# pdf(file = "ggpairs_grouped_year.pdf")
ggpairs(data_factor,
    aes(colour = YEAR),
    upper = list(continuous = wrap("cor", digits = 2)),
    lower = list(combo = wrap("facethist", bins = 10)),
    diag = list(continuous = wrap("barDiag", bins = 10)),
) + ggtitle("ggpairs_grouped_year")
# dev.off()
```

```{r}
# pdf(file = "ggpairs_grouped_origin.pdf")
ggpairs(data_factor,
    aes(colour = ORIGIN),
    upper = list(continuous = wrap("cor", digits = 2)),
    lower = list(combo = wrap("facethist", bins = 10)),
    diag = list(continuous = wrap("barDiag", bins = 10)),
) + ggtitle("ggpairs_grouped_origin")
# dev.off()
```


```{r}
# pdf(file = "cor_matrix_pearson.pdf")
ggplot(melt(cor(data, method = "pearson"))) +
    geom_raster(aes(x = Var2, y = Var1, fill = value)) +
    scale_fill_gradient2() +
    theme_dark() +
    ggtitle("cor_matrix_pearson")
# dev.off()
```

```{r}
# pdf(file = "cor_matrix_spearman.pdf")
ggplot(melt(cor(data, method = "spearman"))) +
    geom_raster(aes(x = Var2, y = Var1, fill = value)) +
    scale_fill_gradient2() +
    theme_dark() +
    ggtitle("cor_matrix_spearman")
# dev.off()
```

```{r}
# pdf(file = "partial_cor_matrix_pearson.pdf")
ggplot(melt(pcor(data, method = "pearson")$estimate)) +
    geom_raster(aes(x = Var2, y = Var1, fill = value)) +
    scale_fill_gradient2() +
    theme_dark() +
    ggtitle("partial_cor_matrix_pearson")
# dev.off()
```

```{r}
# pdf(file = "partial_cor_matrix_spearman.pdf")
ggplot(melt(pcor(data, method = "spearman")$estimate)) +
    geom_raster(aes(x = Var2, y = Var1, fill = value)) +
    scale_fill_gradient2() +
    theme_dark() +
    ggtitle("partial_cor_matrix_spearman")
# dev.off()
```

```{r}
# pdf(file = "partial_cor_matrix_by_cylinder.pdf")
partial_cor_matrix_by_cylinder <- melt(cor(data %>% select(-CYLINDER), method = "pearson"))[, 1:2]
partial_cor_matrix_by_cylinder$value <- (apply(partial_cor_matrix_by_cylinder, 1, function(x) {
    if (x[1] == x[2]) {
        return(1)
    }
    return(pcor.test(data[[as.character(x[1])]], data[[as.character(x[2])]], data$CYLINDER)$estimate)
}))

ggplot(partial_cor_matrix_by_cylinder) +
    geom_raster(aes(x = Var2, y = Var1, fill = value)) +
    scale_fill_gradient2() +
    theme_dark() +
    ggtitle("partial_cor_matrix_by_cylinder")
# dev.off()
```